{
 "title": "Overview",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   { "name": "interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "total",
    "label": "total_servers",
    "query": "query_result(count(node_uname_info))"
   }
  ]
 },
 "panels": [
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{namespace=\"default\",phase=\"Running\"}) by (phase)"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{namespace=\"default\",phase=\"Pending\"}) by (phase)"
    }
   ]
  },
  {
   "title": "Cron",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(kube_cronjob_info)" }
   ]
  },
  {
   "title": "Cron Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(kube_job_status_failed)" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 20, "w": 1, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "metricQuery": { "projectName": "btcraffle-306013" } }
   ]
  },
  {
   "title": "Requests/m",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "grafana-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_request_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "btcraffle-306013",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "metricQuery": { "projectName": "btcraffle-306013" } }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 18, "w": 1, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "metricQuery": { "projectName": "btcraffle-306013" } }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$interval])) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(node_uname_info)" }
   ]
  },
  {
   "title": "Allocatable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 23, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (machine_cpu_cores)" }
   ]
  },
  {
   "title": "Requested",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 23, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes)"
    }
   ]
  },
  {
   "title": "HPA",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_hpa_status_current_replicas"
    },
    {
     "expr": "(kube_hpa_status_current_replicas / kube_hpa_spec_max_replicas) * 100"
    }
   ]
  },
  {
   "title": "API",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "grafana-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_name",
       "=",
       "k8s1-3f5b5560-default-backendv2-80-1f7aeb8a"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_request_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "btcraffle-306013",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "APIv1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "grafana-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_name",
       "=",
       "k8s1-3f5b5560-default-backendv1-80-1dc1d101"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_request_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "btcraffle-306013",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 7 },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes - 0", "legendFormat": "总内存" },
    {
     "expr": "count(node_cpu_seconds_total{mode='system'}) by (instance)",
     "legendFormat": "总核数"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "内存使用率"
    }
   ]
  },
  {
   "title": "UI",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_name",
       "=",
       "k8s1-3f5b5560-default-ui-80-e9fc572d"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_request_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "btcraffle-306013",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "grafana-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_name",
       "=",
       "k8s1-3f5b5560-default-nginx-80-08368314"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_request_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "btcraffle-306013",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"default\",container!~\"hello.*|prom.*|helm.*|kube.*|jump.*|grafana.*\"}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 17, "w": 4, "x": 9, "y": 14 },
   "targets": [
    { "metricQuery": { "projectName": "btcraffle-306013" } }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 11, "x": 13, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "metricQuery": { "projectName": "btcraffle-306013" } }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 9, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "metricQuery": { "projectName": "btcraffle-306013" } }
   ]
  },
  {
   "type": "dashlist",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 21 },
   "targets": [
    { "metricQuery": { "projectName": "btcraffle-306013" } }
   ]
  }
 ]
}