{
 "title": "Pods",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HPA",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "kube_hpa_spec_min_replicas" },
    {
     "expr": "kube_hpa_status_current_replicas"
    },
    { "expr": "kube_hpa_spec_max_replicas" },
    {
     "expr": "(kube_hpa_status_current_replicas / kube_hpa_spec_max_replicas) * 100"
    }
   ]
  },
  {
   "title": "Pods CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{image!=\"\",namespace=\"default\"}[1m])) by (pod)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",namespace=\"default\"}) by (pod)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "type": "dashlist",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 19 },
   "targets": [
    { "metricQuery": { "projectName": "btcraffle-306013" } }
   ]
  }
 ]
}